"use strict";
// Besedila lupine (meniji, pogovorna okna, nastavitve) v slovenščini in angleščini.
// Jezik določi urejevalnik (preklopnik jezika zgoraj desno), lupina ga samo sledi.

const STRINGS = {
  sl: {
    // meni
    "menu.about": "O programu Layerling",
    "menu.settings": "Nastavitve …",
    "menu.hide": "Skrij Layerling",
    "menu.hideOthers": "Skrij ostale",
    "menu.unhide": "Pokaži vse",
    "menu.quitMac": "Končaj Layerling",
    "menu.file": "Datoteka",
    "menu.openProject": "Odpri projekt (.lyl) …",
    "menu.openAutosaveFolder": "Odpri mapo samodejnega shranjevanja",
    "menu.restore": "Obnovi projekte iz samodejnega shranjevanja …",
    "menu.closeWindow": "Zapri okno",
    "menu.exit": "Izhod",
    "menu.edit": "Urejanje",
    "menu.undo": "Razveljavi",
    "menu.redo": "Uveljavi",
    "menu.cut": "Izreži",
    "menu.copy": "Kopiraj",
    "menu.paste": "Prilepi",
    "menu.selectAll": "Izberi vse",
    "menu.view": "Pogled",
    "menu.reload": "Ponovno naloži",
    "menu.zoomIn": "Povečaj vmesnik",
    "menu.zoomOut": "Pomanjšaj vmesnik",
    "menu.resetZoom": "Običajna velikost",
    "menu.fullscreen": "Celozaslonski način",
    "menu.devtools": "Orodja za razvijalce",
    "menu.window": "Okno",
    "menu.help": "Pomoč",
    "menu.checkUpdates": "Preveri posodobitve …",
    "menu.ai": "Povezava z AI (MCP) …",
    "menu.docs": "Navodila (originalna dokumentacija)",
    "menu.source": "Izvorna koda (AGPL-3.0)",
    // posodobitve
    "update.title": "Posodobitev programa",
    "update.available": "Na voljo je nova različica Layerling {version}.",
    "update.current": "Trenutna različica: {version}.",
    "update.askMac": "Odprem stran za prenos?",
    "update.askWin": "Želite jo prenesti in namestiti? Vaši projekti ostanejo nespremenjeni.",
    "update.openPage": "Odpri stran za prenos",
    "update.download": "Prenesi in namesti",
    "update.later": "Pozneje",
    "update.downloadFailed": "Prenos posodobitve ni uspel",
    "update.upToDateTitle": "Posodobitve",
    "update.upToDate": "Imate najnovejšo različico.",
    "update.downloadedTitle": "Posodobitev je prenesena",
    "update.downloaded": "Različica {version} je pripravljena.",
    "update.downloadedDetail": "Program se bo zaprl, namestil posodobitev in se znova zagnal. Projekti se pred tem shranijo.",
    "update.installNow": "Namesti zdaj",
    "update.onExit": "Ob naslednjem izhodu",
    "update.checkFailed": "Preverjanje posodobitev ni uspelo.",
    "update.checkFailedDetail": "Preverite internetno povezavo in poskusite znova.",
    "update.devOnly": "Preverjanje posodobitev deluje samo v nameščenem programu.",
    // pogovorna okna
    "dlg.openFailed": "Datoteke ni mogoče odpreti",
    "dlg.fileTooBig": "Datoteka je prevelika ali ni datoteka.",
    "dlg.portBusyTitle": "Vrata so zasedena",
    "dlg.portBusy": "Vrata {port} že uporablja drug program, zato Layerling ne more teči.\n\nZaprite ta program (ali drugo kopijo Layerlinga) in poskusite znova.",
    "dlg.startFailed": "Program se ni mogel zagnati: {message}",
    "dlg.restoreFoundTitle": "Najdeni shranjeni projekti",
    "dlg.restoreFound": "V programu ni projektov, v mapi samodejnega shranjevanja pa je jih {count}.",
    "dlg.restoreAsk": "Želite jih vrniti v program?",
    "dlg.restoreYes": "Obnovi projekte",
    "dlg.restoreNo": "Ne zdaj",
    "dlg.restoreTitle": "Obnovitev",
    "dlg.restoreNone": "V mapi samodejnega shranjevanja ni projektov.",
    "dlg.autosaveFailed": "Samodejno shranjevanje na disk ni uspelo. Preverite mapo v Nastavitvah.",
    "dlg.aboutTitle": "O programu",
    "dlg.aboutStandalone": "Samostojna različica za {os}.",
    "dlg.aboutBase": "Osnova: Layerling {version}{commit} – github.com/henmedia/layerling,",
    "dlg.aboutLicense": "izpeljanka SketchForge-3D. Licenca: GNU AGPL v3.",
    "dlg.aboutSource": "Izvorna koda: {url}",
    "dlg.aboutBy": "Layerling Desktop: Cassette Deck Service (cassettedeck-service.com).",
    "dlg.openProjectTitle": "Odpri projekt",
    "dlg.openProjectFilter": "Layerling projekt",
    "dlg.allFiles": "Vse datoteke",
    "dlg.pickFolder": "Izberite mapo",
    "dlg.autosaveFolder": "Mapa samodejnega shranjevanja",
    "dlg.sharedFolder": "Skupna mapa",
    "dlg.folderNotWritable": "{label} ni zapisljiva ({folder}): {message}",
    "settings.windowTitle": "Nastavitve – Layerling",
    // okno z nastavitvami
    "s.title": "Nastavitve",
    "s.version": "Layerling {app} · osnova: originalni program {upstream}",
    "s.autosaveTitle": "Samodejno shranjevanje na disk",
    "s.autosaveHint": "Program ves čas hrani projekte v svoji shrambi; tukaj pa jih dodatno zapisuje kot datoteke <b>.lyl</b> v mapo po vaši izbiri. Zapisujejo se samo spremenjeni projekti. Brisanje projekta v programu ne izbriše njegove kopije na disku.",
    "s.autosaveEnabled": "Samodejno shranjuj na disk",
    "s.interval": "Na koliko sekund preveri spremembe",
    "s.intervalRange": "(5–3600 s)",
    "s.folder": "Mapa",
    "s.pick": "Izberi …",
    "s.open": "Odpri",
    "s.keep": "Koliko starejših verzij ohrani",
    "s.keepNote": "za vsak projekt (0 = brez)",
    "s.gap": "Najmanj minut med verzijama",
    "s.lastWrite": "Zadnje zapisovanje: {when}",
    "s.lastWriteFailed": " ({count} ni uspelo)",
    "s.noWriteYet": "Od zagona še ni bilo zapisovanja.",
    "s.sharedTitle": "Skupna mapa (deljenje projektov)",
    "s.sharedHint": "Mapa, ki jo sinhronizira iCloud Drive (ali druga storitev). V programu se prikaže kot razdelek <b>Shared</b>. Hkratno urejanje istega projekta ni mogoče: odprite ga eden naenkrat. Samodejno shranjevanje zgoraj naj kaže v <b>lokalno</b> mapo, ne v oblak.",
    "s.sharedOff": "(izklopljeno)",
    "s.sharedClear": "Izklopi",
    "s.icloudFound": "Najden iCloud Drive",
    "s.sharedReload": "Ob spremembi se bo program na kratko znova naložil.",
    "s.mcpTitle": "Povezava z AI (MCP)",
    "s.mcpHint": "Z njo lahko Claude ali drug odjemalec MCP gradi v odprtem urejevalniku. Povezava je dostopna samo s tega računalnika in zaščitena z žetonom. Vnos prilepite v nastavitve odjemalca (Claude Desktop: Settings → Developer → Edit Config), nato ga znova zaženite.",
    "s.mcpCopy": "Kopiraj nastavitve",
    "s.mcpRegen": "Ustvari nov žeton",
    "s.mcpCopied": "Kopirano.",
    "s.mcpConfirm": "Nov žeton bo razveljavil staro nastavitev v odjemalcu MCP. Nadaljujem?",
    "s.mcpRegenerated": "Žeton je zamenjan; posodobite nastavitve v odjemalcu.",
    "s.updatesTitle": "Posodobitve",
    "s.updatesCheck": "Ob zagonu preveri, ali je na voljo nova različica",
    "s.updatesHint": "Nova različica se nikoli ne namesti brez vaše potrditve.",
    "s.updatesNow": "Preveri zdaj",
    "s.close": "Zapri",
    "s.save": "Shrani",
    "s.saving": "Shranjujem …",
    "s.saved": "Shranjeno.",
    "s.pickAutosave": "Mapa za samodejno shranjevanje",
    "s.pickShared": "Skupna mapa",
    "s.locale": "sl-SI",
  },
  en: {
    "menu.about": "About Layerling",
    "menu.settings": "Settings…",
    "menu.hide": "Hide Layerling",
    "menu.hideOthers": "Hide Others",
    "menu.unhide": "Show All",
    "menu.quitMac": "Quit Layerling",
    "menu.file": "File",
    "menu.openProject": "Open design (.lyl)…",
    "menu.openAutosaveFolder": "Open autosave folder",
    "menu.restore": "Restore designs from autosave…",
    "menu.closeWindow": "Close Window",
    "menu.exit": "Exit",
    "menu.edit": "Edit",
    "menu.undo": "Undo",
    "menu.redo": "Redo",
    "menu.cut": "Cut",
    "menu.copy": "Copy",
    "menu.paste": "Paste",
    "menu.selectAll": "Select All",
    "menu.view": "View",
    "menu.reload": "Reload",
    "menu.zoomIn": "Zoom In",
    "menu.zoomOut": "Zoom Out",
    "menu.resetZoom": "Actual Size",
    "menu.fullscreen": "Full Screen",
    "menu.devtools": "Developer Tools",
    "menu.window": "Window",
    "menu.help": "Help",
    "menu.checkUpdates": "Check for updates…",
    "menu.ai": "AI connection (MCP)…",
    "menu.docs": "User guide (original documentation)",
    "menu.source": "Source code (AGPL-3.0)",
    "update.title": "Software update",
    "update.available": "A new version of Layerling is available: {version}.",
    "update.current": "Current version: {version}.",
    "update.askMac": "Open the download page?",
    "update.askWin": "Do you want to download and install it? Your designs stay untouched.",
    "update.openPage": "Open download page",
    "update.download": "Download and install",
    "update.later": "Later",
    "update.downloadFailed": "The update could not be downloaded",
    "update.upToDateTitle": "Updates",
    "update.upToDate": "You have the latest version.",
    "update.downloadedTitle": "Update downloaded",
    "update.downloaded": "Version {version} is ready.",
    "update.downloadedDetail": "The app will close, install the update and start again. Your designs are saved first.",
    "update.installNow": "Install now",
    "update.onExit": "On next exit",
    "update.checkFailed": "Checking for updates failed.",
    "update.checkFailedDetail": "Check your internet connection and try again.",
    "update.devOnly": "Checking for updates only works in the installed app.",
    "dlg.openFailed": "The file cannot be opened",
    "dlg.fileTooBig": "The file is too large or is not a file.",
    "dlg.portBusyTitle": "Port is in use",
    "dlg.portBusy": "Port {port} is already used by another program, so Layerling cannot run.\n\nClose that program (or another copy of Layerling) and try again.",
    "dlg.startFailed": "The app could not start: {message}",
    "dlg.restoreFoundTitle": "Saved designs found",
    "dlg.restoreFound": "There are no designs in the app, but the autosave folder holds {count}.",
    "dlg.restoreAsk": "Do you want to bring them back into the app?",
    "dlg.restoreYes": "Restore designs",
    "dlg.restoreNo": "Not now",
    "dlg.restoreTitle": "Restore",
    "dlg.restoreNone": "The autosave folder contains no designs.",
    "dlg.autosaveFailed": "Saving to disk failed. Check the folder in Settings.",
    "dlg.aboutTitle": "About",
    "dlg.aboutStandalone": "Standalone version for {os}.",
    "dlg.aboutBase": "Based on: Layerling {version}{commit} – github.com/henmedia/layerling,",
    "dlg.aboutLicense": "derived from SketchForge-3D. License: GNU AGPL v3.",
    "dlg.aboutSource": "Source code: {url}",
    "dlg.aboutBy": "Layerling Desktop: Cassette Deck Service (cassettedeck-service.com).",
    "dlg.openProjectTitle": "Open design",
    "dlg.openProjectFilter": "Layerling design",
    "dlg.allFiles": "All files",
    "dlg.pickFolder": "Choose a folder",
    "dlg.autosaveFolder": "Autosave folder",
    "dlg.sharedFolder": "Shared folder",
    "dlg.folderNotWritable": "{label} is not writable ({folder}): {message}",
    "settings.windowTitle": "Settings – Layerling",
    "s.title": "Settings",
    "s.version": "Layerling {app} · based on the original app {upstream}",
    "s.autosaveTitle": "Autosave to disk",
    "s.autosaveHint": "The app always keeps designs in its own storage; here it additionally writes them as <b>.lyl</b> files to a folder of your choice. Only changed designs are written. Deleting a design in the app does not delete its copy on disk.",
    "s.autosaveEnabled": "Save to disk automatically",
    "s.interval": "Check for changes every",
    "s.intervalRange": "(5–3600 s)",
    "s.folder": "Folder",
    "s.pick": "Choose…",
    "s.open": "Open",
    "s.keep": "Older versions to keep",
    "s.keepNote": "per design (0 = none)",
    "s.gap": "Minutes between versions",
    "s.lastWrite": "Last write: {when}",
    "s.lastWriteFailed": " ({count} failed)",
    "s.noWriteYet": "Nothing has been written since the app started.",
    "s.sharedTitle": "Shared folder (sharing designs)",
    "s.sharedHint": "A folder synced by iCloud Drive (or another service). It appears in the app as the <b>Shared</b> section. Editing the same design at the same time is not possible: open it one person at a time. Autosave above should point to a <b>local</b> folder, not to the cloud.",
    "s.sharedOff": "(off)",
    "s.sharedClear": "Turn off",
    "s.icloudFound": "iCloud Drive found",
    "s.sharedReload": "The app will reload briefly when this changes.",
    "s.mcpTitle": "AI connection (MCP)",
    "s.mcpHint": "Lets Claude or another MCP client build in the open editor. The connection is only reachable from this computer and protected by a token. Paste the entry into the client's settings (Claude Desktop: Settings → Developer → Edit Config), then restart it.",
    "s.mcpCopy": "Copy settings",
    "s.mcpRegen": "Create a new token",
    "s.mcpCopied": "Copied.",
    "s.mcpConfirm": "A new token will invalidate the old setting in the MCP client. Continue?",
    "s.mcpRegenerated": "The token was replaced; update the settings in the client.",
    "s.updatesTitle": "Updates",
    "s.updatesCheck": "Check for a new version at startup",
    "s.updatesHint": "A new version is never installed without your confirmation.",
    "s.updatesNow": "Check now",
    "s.close": "Close",
    "s.save": "Save",
    "s.saving": "Saving…",
    "s.saved": "Saved.",
    "s.pickAutosave": "Autosave folder",
    "s.pickShared": "Shared folder",
    "s.locale": "en-GB",
  },
};

let current = "sl";

function normalizeLanguage(value) {
  return value === "en" || value === "sl" ? value : null;
}

/** Jezik sistema: slovenščina za slovenske sisteme, sicer angleščina. */
function languageFromLocale(locale) {
  return String(locale || "").toLowerCase().startsWith("sl") ? "sl" : "en";
}

function setLanguage(language) {
  current = normalizeLanguage(language) || current;
  return current;
}

function getLanguage() {
  return current;
}

function tr(key, vars) {
  const table = STRINGS[current];
  const template = table[key] ?? STRINGS.en[key] ?? key;
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (match, name) => (Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : match));
}

module.exports = { STRINGS, tr, setLanguage, getLanguage, normalizeLanguage, languageFromLocale };
